In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('titanic_data_updated.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.drop(['PassengerId','Name', 'Ticket'], axis=1,inplace=True)

df.head()

  Survived Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       no  third    male  22.0      1      0   7.2500   NaN        S
1      yes  first  female  38.0      1      0  71.2833   C85        C
2      yes  third  female  26.0      0      0   7.9250   NaN        S
3      yes  first  female  35.0      1      0  53.1000  C123        S
4       no  third    male  35.0      0      0   8.0500   NaN        S

In [4]:
df.isnull().sum()

# df.drop(['Cabin'],axis=1, inplace=True)
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         no   third    male  22.0      1      0   7.2500   NaN        S
1        yes   first  female  38.0      1      0  71.2833   C85        C
2        yes   third  female  26.0      0      0   7.9250   NaN        S
3        yes   first  female  35.0      1      0  53.1000  C123        S
4         no   third    male  35.0      0      0   8.0500   NaN        S
..       ...     ...     ...   ...    ...    ...      ...   ...      ...
886       no  second    male  27.0      0      0  13.0000   NaN        S
887      yes   first  female  19.0      0      0  30.0000   B42        S
888       no   third  female   NaN      1      2  23.4500   NaN        S
889      yes   first    male  26.0      0      0  30.0000  C148        C
890       no   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [5]:
X = df.drop(['Survived'],axis=1 )
X

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0     third    male  22.0      1      0   7.2500   NaN        S
1     first  female  38.0      1      0  71.2833   C85        C
2     third  female  26.0      0      0   7.9250   NaN        S
3     first  female  35.0      1      0  53.1000  C123        S
4     third    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886  second    male  27.0      0      0  13.0000   NaN        S
887   first  female  19.0      0      0  30.0000   B42        S
888   third  female   NaN      1      2  23.4500   NaN        S
889   first    male  26.0      0      0  30.0000  C148        C
890   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [6]:
y = df['Survived']

y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: str

In [7]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\samiu\anaconda3\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\samiu\anaconda3\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\samiu\anaconda3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\samiu\anaconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\samiu\anaconda3\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\samiu\anaconda3\Lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [14]:
X_train
display(y_train)

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: str

In [16]:
X_test
display(y_test)

709    yes
439     no
840     no
720    yes
39     yes
      ...
433     no
773     no
25     yes
84     yes
10     yes
Name: Survived, Length: 179, dtype: str